twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        twig_globals: '@App\Services\TwigGlobals'
when@test:
    twig:
        strict_variables: true
